name: build-and-push-nightly-pytorch-onchange

on:
  push:
    branches: [ "manual-push-nightly" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: image-build-and-push
    steps:
      # docker login source https://github.com/docker/login-action
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          # Note: these values can be configured under https://github.com/foundation-model-stack/base-images/settings/environments/614355731/edit
          username: ${{ secrets.GH_REGISTRY_USER }}
          password: ${{ secrets.GH_REGISTRY_PUSH_TOKEN }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: build and push
        run: ./nightly-pytorch/buildAndPush.sh
